server:
  port: 8004

spring:
  application:
    name: cloud-seckill-service
  cloud:
    nacos:
      server-addr: 81.69.173.67:8848
  datasource:
    url: jdbc:mysql://81.69.173.67:3306/store
    username: root
    password: evivv
    driver-class-name: com.mysql.cj.jdbc.Driver  #MySQL8.0后

    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  redis: #超时时间
    timeout: 10000ms #服务器地址
    host: 81.69.173.67 #服务器端口
    port: 6379 #数据库
    password: evivv
    database: 0
    lettuce:
      pool:
        min-active: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  rabbitmq:
    host: 81.69.173.67 # 主机名
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    listener:
      simple:
        concurrency: 10 # 消费者最小数量
        max-concurrency: 10 #消费者最大数量
        prefetch: 1 # 限制消费者每次只预取一条消息
        auto-startup: true #启动时是否默认启动容器
        default-requeue-rejected: true # 被拒绝时是否进入队列
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms





mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql信息
  global-config:
    db-config:
      table-prefix: t_  # 设置实体类所对应的表的前缀
      id-type: auto # 设置全局自增策略

userinfo:
  address:
    maxCount: 20
